---
sudo: required
language: python
python: "2.7"
cache: pip

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - pip install molecule docker-py

script:
  - molecule test
