---
services: docker

env:
  matrix:
    - distro=centos7 playbook=package-test.yml
    - distro=ubuntu1604 playbook=package-test.yml
    - distro=ubuntu1404 playbook=package-test.yml
    - distro=debian9 playbook=package-test.yml
    - distro=debian8 playbook=package-test.yml

    - distro=centos7 playbook=compile-test.yml
    - distro=ubuntu1604 playbook=compile-test.yml
    - distro=ubuntu1404 playbook=compile-test.yml
    - distro=debian9 playbook=compile-test.yml
    - distro=debian8 playbook=tests/compile-test.yml

matrix:
  exclude:
    - env: distro=debian8
    - env: distro=ubuntu1404

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure dns can be queried.
  - docker exec --tty ${container_id} dig @127.0.0.1 | grep "NOERROR"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

# ---
# sudo: required
# language: python
# python: "2.7"
# cache: pip

# services:
#   - docker

# before_install:
#   - sudo apt-get -qq update

# install:
#   - pip install molecule docker-py

# script:
#   - travis_wait 50 "molecule test"
