---
- name: Install openssl
  package:
    name: openssl
    state: present

- name: Prepare dns-over-tls selfsigned cert
  import_tasks: self-signed.yml
  when: unbound_tls_cert_provider == "selfsigned"

- name: Prepare dns-over-tls with acme and cloudflare
  import_tasks: cloudflare-acme.yml
  when: unbound_tls_cert_provider == "acme-cf"

- name: Prepare dns-over-tls with acme
  import_tasks: acme.yml
  when: unbound_tls_cert_provider == "acme"


- name: Get certificate fingerprint
  shell: "openssl req -pubkey < {{unbound.server.directory}}/request.csr | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64"
  args:
    executable: bash
  register: unbound_fingerprint
  changed_when: false

- name: Display fingerprint and example Stubby config
  debug:
    msg:
      upstream_recursive_servers:
        address_data: "{{ansible_default_ipv4.address if ansible_default_ipv4 is defined else \"<the server's ip address>\"}}"
        tls_auth_name: "{{unbound_tls_domain}}"
        tls_pubkey_pinset:
          digest: "sha256"
          value: "{{unbound_fingerprint.stdout}}"
  when: not ansible_check_mode
