---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos
    image: centos
  # - name: freebsd
  #   image: auchida/freebsd:11
  - name: ubuntu
    image: ubuntu
  - name: debian
    image: debian
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - lint
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
