---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: fedora24
    image: geerlingguy/docker-fedora24-ansible  # patched init
    command: "/usr/lib/systemd/systemd"
    privileged: true
  - name: centos7  # ipv6 not working
    image: geerlingguy/docker-centos7-ansible  # patched init
    command: "/usr/lib/systemd/systemd"
    privileged: true
  # - name: centos6
  #   image: geerlingguy/docker-centos6-ansible  # patched init
  #   command: "/sbin/init"
  #   privileged: true
  - name: ubuntu16.04-xenial
    image: geerlingguy/docker-ubuntu1604-ansible  # patched init
    command: "/lib/systemd/systemd"
    privileged: true
  # - name: ubuntu14.04-trusty
  #   image: geerlingguy/docker-ubuntu1404-ansible  # patched init
  #   command: "/sbin/init"
  #   privileged: true
  - name: debian9-stretch
    image: geerlingguy/docker-debian9-ansible  # patched init
    command: "/lib/systemd/systemd"
    privileged: true
  - name: debian8-jessie
    image: geerlingguy/docker-debian8-ansible  # patched init
    command: "/lib/systemd/systemd"
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - lint
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
